### ISSUE TITLE
Highlighting Resoluting scaling

### ISSUE THREAD

**Issue by EdwoG** [darvid/stashvision#13]
Hi, im the guy who pm'd you on reddit.

First time coding so i hesitated but i rewrote some code to fix the issue with highlights being cut off on different resolutions.

I removed all the resolution numbers and based everything only the window height and percentage based distance
This should fix it for widescreen aswell.

Original code.

> GetStashPosition(ByRef stashX, ByRef stashY, ByRef stashWidth, ByRef stashHeight) {
>     WinGetPos, poeX, poeY, poeWidth, poeHeight, Path of Exile
>     stashXroot := 23/2560
>     stashYroot := 216/1440
>     stashX := Round(poeWidth * stashXroot)
>     stashY := Round(poeHeight * stashYroot)
>     stashWidth := Round(poeWidth * 0.33)
>     stashHeight := poeHeight - stashY - 380
> _____________________________________________________
> HighlightItem(stashX, stashY, stashWidth, stashHeight, hwnd, graphics, hdc, width, height, x, y, isQuadTab, borderColor) {
>     if isQuadTab {
>         rectWidth := 35
>         rectHeight := 35
>     } else {
>         rectWidth := 70
>         rectHeight := 70

Changed code to

> GetStashPosition(ByRef stashX, ByRef stashY, ByRef stashWidth, ByRef stashHeight) {
>     WinGetPos, poeX, poeY, poeWidth, poeHeight, Path of Exile
>     stashXroot := .0148148148148148
>     stashYroot := .15
>     stashX := Round(stashXroot * poeHeight)
>     stashY := Round(stashYroot * poeHeight)
>     stashWidth := poeHeight * .587
>     stashHeight := poeHeight * .58611
> _____________________________________________________
> HighlightItem(stashX, stashY, stashWidth, stashHeight, hwnd, graphics, hdc, width, height, x, y, isQuadTab, borderColor) {
>     if isQuadTab {
>         rectWidth :=  stashWidth * .041485
>         rectHeight := stashWidth * .041485
>     } else {
>         rectWidth := stashWidth * .08297
>         rectHeight := stashHeight * .08297

here is a pastbin to the entire file: https://pastebin.com/C5pyXrXV

**Comment by darvid** [comment]
cool - I noticed other issues with calculating stash tab height as well which may be causing highlighted item squares to get clipped at different resolutions. If you could try the [`stashvision.ahk` from the latest commit](https://raw.githubusercontent.com/darvid/stashvision/3be7c9994d288dd30811556e3a99d31a36b40f36/stashvision.ahk) and let me know if that works, I think it should address both the positioning and the sizing issues. 

Your changes look fine, although from my testing it seemed like the starting x position of the stash is always the same, regardless of resolution. On my ultrawide, using the ratio to calculate starting x position resulted in it being off at different resolutions.

**Comment by EdwoG** [comment]
![highlights](https://user-images.githubusercontent.com/56611968/93284360-cfd11380-f7d2-11ea-9b8a-59fdffe2dbae.PNG)
it looked like this on other resolutions too.
i tought it might be more monitor depended to be exact since it doesnt change much with resolution, but i guess i did for you

the people i tried my code with say it worked well and they had

1440 x 3440
1080 x 3440
and mine is 1980 x 1080

they probably had highest resolution or atleast 1080 since did say nothing but cant say for sure, whats your monior?

**Comment by darvid** [comment]
OK let's just use your values for now, it looks close enough for me, although the y is slightly off on my end. 

![image](https://user-images.githubusercontent.com/569269/93290528-ee251800-f7ae-11ea-8a01-a67b7944cea0.png)

try this: https://raw.githubusercontent.com/darvid/stashvision/dc8e3b7fcd46695275d458a0f7caa4cc3e3cd732/stashvision.ahk
if it still looks good for you, I'll go ahead and release a new version before Heist start.

at this point I think trying to calculate the position perfectly is going to be inaccurate because of all the different variables (resolution, DPI scaling, poe display modes), when I have more time to work on this I'll try to explore another way of detecting the stash window more reliably. I have a few ideas for that but unfortunately not a lot of time.

thanks for your help with this one! my only other comment is, do you have the actual factors you used to get the x and y roots?
 i.e. 23/1440. I'd prefer to use them instead of the hard-coded integers if possible.

**Comment by EdwoG** [comment]
![image](https://user-images.githubusercontent.com/56611968/93291361-247c8a80-f7e3-11ea-8ee7-4cdbe6c79bf9.png)
super small cutoff, i mean this is good enough by now. just  a little unclean

x 16 / 1080 and y 162 / 1080
i dont remember fully, but i think i meassured those numbers manually (lol) its at most 1 pixel off, shouldnt impact much

jesus i can barly remember what i did, so many numbers
