### ISSUE TITLE
Overlay not showing up

### ISSUE THREAD

**Issue by DrLeoMarvin** [darvid/stashvision#7]
server.log shows the items being indexed properly after manually changing league to standard since the AHK is ignoring that part of the ini file

Neither chaos recipe or search seems to work

**Comment by darvid** [comment]
what's your game resolution and display mode? the highlight overlay won't show up if you don't have enough items for the recipe in your tab, but the search window should always show up with the assigned hotkey. can you paste your config file?

also the config file takes LeagueName not League, my mistake, should be fixed now in the sample config

**Comment by DrLeoMarvin** [comment]
2560x1440
Directx11
Windowed Fullscreen

[stashvision.ini.test.txt](https://github.com/darvid/stashvision/files/4802108/stashvision.ini.test.txt)
Ignore the garbage extensions. I modified the config to get my account and id out of there

**Comment by darvid** [comment]
that's the same resolution and mode as mine, so even if it was broken for other resolutions it should work for you...

hmm. can you try the following:

* close stashvision
* delete **stashvision-go/stash_tabs.bleve**
* restart stashvision

give it a few seconds then try to use the hotkeys. search should *always* show up...

did you change anything else in the AHK mistakenly while hardcoding the league (I'm assuming you did since you mentioned the INI being ignored)?

**Comment by DrLeoMarvin** [comment]
The search box always shows up as you mentioned. Just never finds anything. I only changed Harvest to Standard

**Comment by DrLeoMarvin** [comment]
I'm assuming tabindex is 0 based so it's the first tab across the top? Just checking simple stuff

**Comment by DrLeoMarvin** [comment]
Found the issue. The stash order in game and from the API is different. The API thinks my first tab is second so I changed the index to 1 and it worked. Thanks for the fast responses!
